apiVersion: 1

datasources:
  - name: if_flow_clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      defaultDatabase: ${CLICKHOUSE_DB}
      host: ${CLICKHOUSE_SERVICE_HOST}
      port: 8123
      protocol: http
      secure: false
      username: ${CLICKHOUSE_USER}
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
